server:  port: 8088  servlet:    context-path: /

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test        mvc:    view:      suffix: .jsp      prefix: WEB-INF/views/    